// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJdODUUBpT9UvH0gTM9h2l3fCpEBFS2M',
    appId: '1:575480319541:web:4a92912f4950a3624dab7c',
    messagingSenderId: '575480319541',
    projectId: 'sign-ab364',
    authDomain: 'sign-ab364.firebaseapp.com',
    storageBucket: 'sign-ab364.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDwpyf59t79zgUpjYqhTSgEDjCVFMJ2k',
    appId: '1:575480319541:android:cd5dc1efacc221894dab7c',
    messagingSenderId: '575480319541',
    projectId: 'sign-ab364',
    storageBucket: 'sign-ab364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOyiEvifbvrJCa0MuL5JJfWk1qmDhCohU',
    appId: '1:575480319541:ios:005c8867f66e3d914dab7c',
    messagingSenderId: '575480319541',
    projectId: 'sign-ab364',
    storageBucket: 'sign-ab364.appspot.com',
    iosBundleId: 'com.example.sign',
  );
}
